[tool.poetry]
name = "polugins"
version = "0.1.1"
description = ""
authors = ["StefanBRas <gitcommits@bruhn.io>"]
readme = "README.md"
packages = [{include = "polugins", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
polars = "^0.18.0"
importlib-metadata = "^6.6.0"
example-package = {path = "tests/pkgs/example_package"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."polugins.lazyframe"]
"internal" = "polugins.namespace:EntryPointNameSpace"
# TODO remember to remove this lol. If not, every one installing it will
# get this namespace attached to their frame
