version: '3'

tasks:
  gen:
    cmds:
      - poetry run python scripts/generate_polars_stubs.py

  test:
    cmds:
      - poetry run pytest

  format:
    cmds:
      - poetry run ruff format .
      - poetry run ruff check . --fix

  lint:
    cmds:
      - poetry run ruff check .
