name: Create stubs

on:
  # schedule:
  #   - cron: '16 5 * * *' # Once a day
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./polugins_type_gen

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Run image
      uses: abatilo/actions-poetry@v2
    - name: Install dependencies
      run: |
        poetry install --only dev
    - name: Create Stubs
      run: |
        poetry run python scripts/generate_polars_stubs.py ${{ github.workspace }}/pr_body.md 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        body-path: ${{ github.workspace }}/pr_body.md
        add-paths: |
            **/*.pyi



